diagnosis/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientDiagnosisListView, DiagnosisCreateStepOneView, DiagnosisCreateStepOneViewWithID, \
    DiagnosisCreateStepTwoView, DiagnosisEditView

app_name = 'diagnosis'

urlpatterns = [
    path('list/', login_required(PatientDiagnosisListView.as_view()), name='diagnosis_list'),
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientDiagnosisListView.as_view()), name='diagnosis_list_period'),
    path('create_one/', login_required(DiagnosisCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(DiagnosisCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(DiagnosisCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(DiagnosisEditView.as_view()), name='diagnosis_edit'),
]

dicts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DictsView, CityListView, CityEditView, CityCreateView, CityDeleteView, \
    EtrapListView, EtrapEditView, EtrapCreateView, EtrapDeleteView, \
    Education_institutionListView, Education_institutionEditView, Education_institutionCreateView, \
    Education_institutionDeleteView, OrganizationListView, OrganizationEditView, OrganizationCreateView, \
    OrganizationDeleteView, HospitalListView, HospitalEditView, HospitalCreateView, HospitalDeleteView, DoctorListView, \
    DoctorEditView, DoctorCreateView, DoctorDeleteView, UnitListView, UnitEditView, UnitCreateView, UnitDeleteView, \
    load_cities, SurgeryTypeListView, SurgeryTypeEditView, SurgeryTypeDeleteView, SurgeryTypeCreateView

app_name = 'dicts'

urlpatterns = [
    path('', login_required(DictsView.as_view()), name='dicts_list'),

    path('city/', login_required(CityListView.as_view()), name='city_list'),
    path('city/edit/<int:pk>/', login_required(CityEditView.as_view()), name='city_edit'),
    path('city/delete/<int:pk>/', login_required(CityDeleteView.as_view()), name='city_delete'),
    path('city/create/', login_required(CityCreateView.as_view()), name='city_create'),
    path('city/load_cities/', load_cities, name='load_cities'),

    path('etrap/', login_required(EtrapListView.as_view()), name='etrap_list'),
    path('etrap/edit/<int:pk>/', login_required(EtrapEditView.as_view()), name='etrap_edit'),
    path('etrap/delete/<int:pk>/', login_required(EtrapDeleteView.as_view()), name='etrap_delete'),
    path('etrap/create/', login_required(EtrapCreateView.as_view()), name='etrap_create'),

    path('education/', login_required(Education_institutionListView.as_view()), name='education_list'),
    path('education/edit/<int:pk>/', login_required(Education_institutionEditView.as_view()), name='education_edit'),
    path('education/delete/<int:pk>/', login_required(Education_institutionDeleteView.as_view()), name='education_delete'),
    path('education/create/', login_required(Education_institutionCreateView.as_view()), name='education_create'),

    path('organization/', login_required(OrganizationListView.as_view()), name='organization_list'),
    path('organization/edit/<int:pk>/', login_required(OrganizationEditView.as_view()), name='organization_edit'),
    path('organization/delete/<int:pk>/', login_required(OrganizationDeleteView.as_view()), name='organization_delete'),
    path('organization/create/', login_required(OrganizationCreateView.as_view()), name='organization_create'),

    path('hospital/', login_required(HospitalListView.as_view()), name='hospital_list'),
    path('hospital/edit/<int:pk>/', login_required(HospitalEditView.as_view()), name='hospital_edit'),
    path('hospital/delete/<int:pk>/', login_required(HospitalDeleteView.as_view()), name='hospital_delete'),
    path('hospital/create/', login_required(HospitalCreateView.as_view()), name='hospital_create'),

    path('doctor/', login_required(DoctorListView.as_view()), name='doctor_list'),
    path('doctor/edit/<int:pk>/', login_required(DoctorEditView.as_view()), name='doctor_edit'),
    path('doctor/delete/<int:pk>/', login_required(DoctorDeleteView.as_view()), name='doctor_delete'),
    path('doctor/create/', login_required(DoctorCreateView.as_view()), name='doctor_create'),

    path('unit/', login_required(UnitListView.as_view()), name='unit_list'),
    path('unit/edit/<int:pk>/', login_required(UnitEditView.as_view()), name='unit_edit'),
    path('unit/delete/<int:pk>/', login_required(UnitDeleteView.as_view()), name='unit_delete'),

    path('surgery_type/', login_required(SurgeryTypeListView.as_view()), name='surgery_type_list'),
    path('surgery_type/edit/<int:pk>/', login_required(SurgeryTypeEditView.as_view()), name='surgery_type_edit'),
    path('surgery_type/delete/<int:pk>/', login_required(SurgeryTypeDeleteView.as_view()), name='surgery_type_delete'),
    path('surgery_type/create/', login_required(SurgeryTypeCreateView.as_view()), name='surgery_type_create'),
]

health/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView

from health import settings

urlpatterns = [
    # path('', TemplateView.as_view(template_name='main_page/main_page.html'), name='main_page'),
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('patients/', include('patients.urls')),
    path('therapy/', include('therapy.urls')),
    path('surgery/', include('surgery.urls')),
    path('investment/', include('investment.urls')),
    path('dicts/', include('dicts.urls')),
    path('diagnosis/', include('diagnosis.urls')),
    path('resolution/', include('resolution.urls')),
    path('reports/', include('reports.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
]
              #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

patients/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientListView, PatientCreateFormView, PatientEditFormView, PatientDeleteView

app_name = 'patients'

urlpatterns = [
    path('list/', login_required(PatientListView.as_view()), name='patient_list'),
    path('create/', login_required(PatientCreateFormView.as_view()), name='patient_create'),
    path('edit/<int:pk>/', login_required(PatientEditFormView.as_view()), name='patient_edit'),
    path('delete/<int:pk>/', login_required(PatientDeleteView.as_view()), name='patient_delete'),
]

resolution/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientResolutionListView, PatientResolutionCreateFormView, PatientResolutionEditFormView

app_name = 'resolutions'

urlpatterns = [
    path('list/', login_required(PatientResolutionListView.as_view()), name='resolution_list'),
    path('create/', login_required(PatientResolutionCreateFormView.as_view()), name='resolution_create'),
    path('edit/<int:pk>/', login_required(PatientResolutionEditFormView.as_view()), name='resolution_edit'),
    # path('delete/<int:pk>/', login_required(PatientDeleteView.as_view()), name='patient_delete'),
]

surgery/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from .views import PatientSurgeryListView, SurgeryCreateStepOneView, SurgeryCreateStepOneViewWithID, \
    SurgeryCreateStepTwoView, SurgeryEditView

app_name = 'surgery'

urlpatterns = [
    path('list/', login_required(PatientSurgeryListView.as_view()), name='surgery_list'),
    # re_path('list/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)$',
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientSurgeryListView.as_view()), name='surgery_list_period'),
    path('create_one/', login_required(SurgeryCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(SurgeryCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(SurgeryCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(SurgeryEditView.as_view()), name='surgery_edit'),
]

therapy/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientTherapyListView, TherapyCreateStepOneView, TherapyCreateStepTwoView, \
    TherapyCreateStepOneViewWithID, TherapyEditView


app_name = 'therapy'

urlpatterns = [
    path('list/', login_required(PatientTherapyListView.as_view()), name='therapy_list'),
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientTherapyListView.as_view()), name='therapy_list_period'),
    path('create_one/', login_required(TherapyCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(TherapyCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(TherapyCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(TherapyEditView.as_view()), name='therapy_edit'),
]

patients/models.py
from django.db import models

from health.utils import get_data_lang
from dicts.models import City, Education_institution, Sex, Etrap


class Patient(models.Model):
    id = models.AutoField(primary_key=True)
    fullname_0 = models.CharField(max_length=150, blank=True, null=True)
    fullname_1 = models.CharField(max_length=150, blank=True, null=True)
    fullname_2 = models.CharField(max_length=150, blank=True, null=True)

    comment_0 = models.CharField(max_length=250, blank=True, null=True)
    comment_1 = models.CharField(max_length=250, blank=True, null=True)
    comment_2 = models.CharField(max_length=250, blank=True, null=True)

    address_0 = models.CharField(max_length=250, blank=True, null=True)
    address_1 = models.CharField(max_length=250, blank=True, null=True)
    address_2 = models.CharField(max_length=250, blank=True, null=True)

    etrap = models.ForeignKey(Etrap, on_delete=models.PROTECT, to_field='id', related_name='relation_patient_etrap',
                              default=None, null=True)
    city = models.ForeignKey(City, on_delete=models.PROTECT, to_field='id', related_name='relation_patient_city',
                             default=None, null=True)

    sex = models.ForeignKey(Sex, on_delete=models.PROTECT, to_field='id', default=None, null=True)
    education_institution = models.ForeignKey(Education_institution, on_delete=models.PROTECT, to_field='id',
                                              default=None, null=True)

    date_birthday = models.DateField(blank=True, null=True)

    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        managed = True
        db_table = 'patient'
        verbose_name_plural = 'Пациенты'
        verbose_name = 'Пациент'
        ordering = ['-created_at',]

    def __str__(self):
        return f'{self.fullname}., {self.date_birthday}'

    @property
    def fullname(self):
        if get_data_lang() == 'en':
            return self.fullname_0
        elif get_data_lang() == 'tk':
            return self.fullname_2
        else:
            return self.fullname_1

    @property
    def address(self):
        if get_data_lang() == 'en':
            return self.address_0
        elif get_data_lang() == 'tk':
            return self.address_2
        else:
            return self.address_1

    @property
    def comment(self):
        if get_data_lang() == 'en':
            return self.comment_0
        elif get_data_lang() == 'tk':
            return self.comment_2
        else:
            return self.comment_1


patients/views.py
from django.urls import reverse_lazy, resolve
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, FormView
from django.views.generic.edit import FormMixin

from diagnosis.models import PatientDiagnosis
from health.utils import get_data_lang
from resolution.models import PatientResolution
from surgery.models import PatientSurgery
from .models import Patient
from .forms import PatientForm, PatientSearchForm
from therapy.models import PatientTherapy
from health.settings import LIST_PAGE_SIZE


class PatientListView(ListView):
    queryset = Patient.objects.order_by('-created_at')
    template_name = 'patients/patient_list.html'
    paginate_by = LIST_PAGE_SIZE
    context_object_name = 'patient_list'

    def get_context_data(self, *args, object_list=None, **kwargs):
        context = super().get_context_data(*args, object_list=object_list, **kwargs)
        context['form'] = PatientSearchForm()
        return context

    def post(self, request, *args, **kwargs):
        self.object_list = Patient.objects.order_by('-created_at')

        fullname = request.POST.get('fullname', '')
        if len(fullname) > 0:
            if get_data_lang() == 'en':
                self.object_list = self.object_list.filter(fullname_0__icontains=fullname).order_by('fullname_0')
            elif get_data_lang() == 'tk':
                self.object_list = self.object_list.filter(fullname_2__icontains=fullname).order_by('fullname_2')
            else:
                self.object_list = self.object_list.filter(fullname_1__icontains=fullname).order_by('fullname_1')

        etrap = request.POST.get('etrap', '')
        if len(etrap) > 0:
            self.object_list = self.object_list.filter(city__etrap_id=etrap)

        year = request.POST.get('year_birthday', '')
        if len(year) > 0:
            self.object_list = self.object_list.filter(date_birthday__year=year)

        return self.render_to_response(self.get_context_data())


class PatientCreateFormView(CreateView):
    template_name = 'patients/patient_edit.html'
    form_class = PatientForm
    success_url = reverse_lazy('patients:patient_list')


class PatientEditFormView(UpdateView):
    template_name = 'patients/patient_edit.html'
    form_class = PatientForm
    model = Patient
    success_url = reverse_lazy('patients:patient_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        therapy = PatientTherapy.objects.filter(patient=self.object)
        context['therapy_list'] = therapy if therapy.count() > 0 else None
        surgery = PatientSurgery.objects.filter(patient=self.object)
        context['surgery_list'] = surgery if surgery.count() > 0 else None
        diagnosis = PatientDiagnosis.objects.filter(patient=self.object)
        context['diagnosis_list'] = diagnosis if diagnosis.count() > 0 else None
        resolution = PatientResolution.objects.filter(patient=self.object)
        context['resolution'] = resolution[0] if resolution.count() > 0 else None
        return context

class PatientDeleteView(DeleteView):
    model = Patient
    success_url = reverse_lazy('patients:patient_list')

templates/patients/patient_confirm_delete.html
{% extends 'base.html' %}
{%  block content %}
{% load i18n %}

<form method="post">{% csrf_token %}
    <p class="h4" style="padding-bottom: 2vh;">{% trans "Вы действительно ходите удалить пациента?" %} "
        {{ object.fullname }}."?</p>
    {{ form }}
    <input type="submit" class="btn btn-danger" value="{% trans "Удалить" %}">
    <a type="submit" class="btn btn-secondary" onclick="history.back()">{% trans "Отмена" %}</a>
</form>
{% endblock %}

templates/patients/patient_diagnosis_list.html
{% load i18n %}
{% if diagnosis_list %}
<div class="container " style="padding-top: 2vh">

    <div class="table">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-header">
                        <h5 class="h5 text-primary"> {% trans "Диагностика" %} </h5>
                    </div>
                    <div class="card-body">
                    <div class="table-responsive">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th scope="col">{% trans "Добавлено" %}</th>
                                    <th scope="col">{% trans "Диагноз" %}</th>
                                    <th scope="col">{% trans "Больница" %}</th>
                                    <th scope="col">{% trans "Дата выписки из стационара" %}</th>
                                    <th scope="col">{% trans "Врач" %}</th>
                                    <th scope="col">{% trans "Проведенные мероприятия" %}</th>
                                    <th scope="col">{% trans "Стоимость" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in diagnosis_list %}
                                <tr>
                                    <td ><a href="{% url 'diagnosis:diagnosis_edit' record.id %}">
                                            {{ record.created_at|date:'d-m-Y H:i' }}
                                        </a>
                                    </td>
                                    <td style="min-width: 20vw;">{{ record.diagnosis|truncatechars:100|default_if_none:'' }}</td>
                                    <td >{{ record.hospital|default_if_none:'' }}</td>
                                    <td >{{ record.exit_date|date:'d-m-Y' }}</td>
                                    <td >{{ record.doctor_diagnosis|default_if_none:'' }}</td>
                                    <td style="min-width: 15vw;">{{ record.diagnosis_description|truncatechars:100|default_if_none:'' }}</td>
                                    <td >{{ record.price_man }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                        {% if is_paginated %}
                            <div class="pagination justify-content-center">
                                <span class="page-link">
                                    {% if page_obj.has_previous %}
                                        <a href="{% url 'surgery:surgery_list' %}?page={{ page_obj.previous_page_number }}"> {% trans "Предыдущая" %} </a>
                                    {% endif %}
                                    <span class="text-black-50">
                                        <span style="padding: 1em">{{ page_obj.number }}</span>
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{% url 'surgery:surgery_list' %}?page={{ page_obj.next_page_number }}"> {% trans "Следующая" %} </a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
{% endif %}

templates/patients/patient_edit.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}

    <form method="post" >
        {% if not error is None %}
            <p class="text-danger">{% trans "Ошибка" %}: {{ error|default_if_none:'' }} </p>
        {% endif %}
        <div class="col-5">
            <p class="text-primary h5" style="padding-bottom: 1vh">
                {% if object.id %}
                    {% trans "Пациент" %}: {{ object.fullname }}
                {% else %}
                    {% trans "Новый пациент" %}
                {% endif %}
            </p>
        </div>
            {% crispy form %}
    </form>
    {% if object.id %}
        <div class="row">
            <a href="{% url 'surgery:create_two'%}?patient_id={{ object.id }}">{% trans "Добавить запись об операции" %}</a>
        </div>
        <div class="row">
            <a href="{% url 'therapy:create_two'%}?patient_id={{ object.id }}">{% trans "Добавить запись о лечении" %}</a>
        </div>
        <div class="row">
            <a href="{% url 'diagnosis:create_two'%}?patient_id={{ object.id }}">{% trans "Добавить запись о диагностике" %}</a>
        </div>
        {% include 'patients/patient_resolution.html' %}
        {% include 'patients/patient_therapy_list.html' %}
        {% include 'patients/patient_surgery_list.html' %}
        {% include 'patients/patient_diagnosis_list.html' %}
    {% endif %}
{% endblock %}

{% block additional_script %}
    <script>
        $("#id_etrap").change(function () {
            var url = "{% url 'dicts:load_cities' %}";
            var etrapId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'etrap': etrapId
                },
                success: function (data) {
                    $("#id_city").html("");
                    for (var i = 0; i < data.length; i++) {
                        var option = new Option(data[i].name, data[i].id);
                        $("#id_city").append(option);
                    }
                }
            });
        });
        </script>
{% endblock %}

templates/patients/patient_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}


{% block content %}

<div class="container" style="padding-top: 2vh">
    <div class="table">
        {% include 'patient_menu.html' %}
        <div class="row" style="padding-bottom: 1vh;">
            <div class="col-1">
                <div class="col btn btn-light">
                    <a class="bg-transparent text-decoration-none text-black"
                       href="{% url 'patients:patient_create' %}">
                        <img src="{% static "images/add_blue.png" %}" height="36" width="36" alt="">
                    </a>
                </div>
            </div>
            <div class="col-10">
                <form method="post" >
                    {% crispy form %}

                </form>

            </div>
        </div>

        <div class="row">
            <div class="col">

                <div class="card">
                    <div class="card-body">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">{% trans "Имя и фамилия пациента" %}</th>
                                    <th scope="col">{% trans "Учебное заведение" %}</th>
                                    <th scope="col">{% trans "Домашний адрес" %}</th>
                                    <th scope="col">{% trans "Дата рождения" %}</th>
                                    <th scope="col">{% trans "Добавлен" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for patient in patient_list %}
                                <tr class="pointer" onclick="document.location = '{% url 'patients:patient_edit' patient.id %}';">
                                    <td scope="row" >
                                            {{ patient.fullname }}
                                    </td>
                                    <td >{{ patient.education_institution.name|default_if_none:'' }}</td>
                                    <td >{{ patient.etrap.name|default_if_none:'' }} {% if patient.etrap.name %}, {% endif %}
                                         {{ patient.city.name|default_if_none:'' }} {% if patient.city.name %}, {% endif %}
                                         {{ patient.address|default_if_none:'' }}</td>
                                    <td >{{ patient.date_birthday|date:'d-m-Y' }}</td>
                                    <td >{{ patient.created_at|date:'d-m-Y H:i' }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                        {% include 'pagination.html' %}
                    </div>
                </div>

            </div>
        </div>

    </div>


</div>

{% endblock %}

templates/patients/patient_resolution.html
{% load i18n %}
{% if resolution %}
<div class="container " style="padding-top: 2vh">

    <div class="table">

        <div class="row">
            <div class="col">

                <div class="card">
                    <div class="card-header">
                        <h5 class="h5 text-primary"> {% trans "Решение" %} </h5>
                    </div>
                    <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <th scope="col">{% trans "Фамилия" %}</th>
                                    <th scope="col">{% trans "Имя" %}</th>
                                    <th scope="col">{% trans "Дата поступления" %}</th>
                                    <th scope="col">{% trans "Дата выдачи решения" %}</th>
                                    <th scope="col">{% trans "Дата свид. о рожд." %}</th>
                                    <th scope="col">{% trans "Добавлено" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr class="pointer" onclick="document.location = '{% url 'resolutions:resolution_edit' resolution.id %}';">

                                    <td >{{ resolution.lastname|default_if_none:'' }}</td>
                                    <td >{{ resolution.resolution_name|default_if_none:'' }}</td>
                                    <td >{{ resolution.income_date|date:'d-m-Y' }}</td>
                                    <td >{{ resolution.resolution_date|date:'d-m-Y' }}</td>
                                    <td >{{ resolution.birth_certificate_date|date:'d-m-Y' }}</td>
                                    <td > {{ resolution.created_at|date:'d-m-Y H:i' }} </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
{% endif %}

templates/patients/patient_surgery_list.html
{% load i18n %}
{% if surgery_list %}
<div class="container " style="padding-top: 2vh">

    <div class="table">

        <div class="row">
            <div class="col">

                <div class="card">
                    <div class="card-header">
                        <h5 class="h5 text-primary"> {% trans "Операции" %} </h5>
                    </div>
                    <div class="card-body">
                    <div class="table-responsive">
                        <table class="table ">
                            <thead>
                                <tr>
                                    <th scope="col">{% trans "Добавлено" %}</th>
                                    <th scope="col">{% trans "Диагноз" %}</th>
                                    <th scope="col">{% trans "Больница, проводящая лечение" %}</th>
                                    <th scope="col">{% trans "Дата госпитализации" %}</th>
                                    <th scope="col">{% trans "Больница и отделение, где проводится операция" %}</th>
                                    <th scope="col">{% trans "Дата операции" %}</th>
                                    <th scope="col">{% trans "Дата выписки из стационара" %}</th>
                                    <th scope="col">{% trans "Оперировавший врач" %}</th>
                                    <th scope="col">{% trans "Анестезиолог" %}</th>
                                    <th scope="col">{% trans "Медсестра" %}</th>
                                    <th scope="col">{% trans "Используемые медикаменты" %}</th>
                                    <th scope="col">{% trans "Стоимость лечения" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for record in surgery_list %}
                                <tr>
                                    <td ><a href="{% url 'surgery:surgery_edit' record.id %}">
                                            {{ record.created_at|date:'d-m-Y H:i' }}
                                        </a>
                                    </td>
                                    <td style="min-width: 20vw;">{{ record.diagnosis|truncatechars:100|default_if_none:'' }}</td>
                                    <td >{{ record.hospital_therapy|default_if_none:'' }}</td>
                                    <td >{{ record.income_date|date:'d-m-Y' }}</td>
                                    <td >
                                        {{ record.hospital_surgery|default_if_none:'' }},
                                        {{ record.department_surgery|default_if_none:'' }}
                                    </td>
                                    <td >{{ record.surgery_date|date:'d-m-Y' }}</td>
                                    <td >{{ record.exit_date|date:'d-m-Y' }}</td>
                                    <td >{{ record.doctor_surgery|default_if_none:'' }}</td>
                                    <td >{{ record.doctor_anestesia|default_if_none:'' }}</td>
                                    <td >{{ record.nurse|default_if_none:'' }}</td>
                                    <td style="min-width: 15vw;">{{ record.medicine_description|truncatechars:100|default_if_none:'' }}</td>
                                    <td >{{ record.price_man }}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                        {% if is_paginated %}
                            <div class="pagination justify-content-center">
                                <span class="page-link">
                                    {% if page_obj.has_previous %}
                                        <a href="{% url 'surgery:surgery_list' %}?page={{ page_obj.previous_page_number }}"> {% trans "Предыдущая" %} </a>
                                    {% endif %}
                                    <span class="text-black-50">
                                        <span style="padding: 1em">{{ page_obj.number }}</span>
                                    </span>
                                    {% if page_obj.has_next %}
                                        <a href="{% url 'surgery:surgery_list' %}?page={{ page_obj.next_page_number }}"> {% trans "Следующая" %} </a>
                                    {% endif %}
                                </span>
                            </div>
                        {% endif %}
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
{% endif %}