diagnosis/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientDiagnosisListView, DiagnosisCreateStepOneView, DiagnosisCreateStepOneViewWithID, \
    DiagnosisCreateStepTwoView, DiagnosisEditView

app_name = 'diagnosis'

urlpatterns = [
    path('list/', login_required(PatientDiagnosisListView.as_view()), name='diagnosis_list'),
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientDiagnosisListView.as_view()), name='diagnosis_list_period'),
    path('create_one/', login_required(DiagnosisCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(DiagnosisCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(DiagnosisCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(DiagnosisEditView.as_view()), name='diagnosis_edit'),
]

dicts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DictsView, CityListView, CityEditView, CityCreateView, CityDeleteView, \
    EtrapListView, EtrapEditView, EtrapCreateView, EtrapDeleteView, \
    Education_institutionListView, Education_institutionEditView, Education_institutionCreateView, \
    Education_institutionDeleteView, OrganizationListView, OrganizationEditView, OrganizationCreateView, \
    OrganizationDeleteView, HospitalListView, HospitalEditView, HospitalCreateView, HospitalDeleteView, DoctorListView, \
    DoctorEditView, DoctorCreateView, DoctorDeleteView, UnitListView, UnitEditView, UnitCreateView, UnitDeleteView, \
    load_cities, SurgeryTypeListView, SurgeryTypeEditView, SurgeryTypeDeleteView, SurgeryTypeCreateView

app_name = 'dicts'

urlpatterns = [
    path('', login_required(DictsView.as_view()), name='dicts_list'),

    path('city/', login_required(CityListView.as_view()), name='city_list'),
    path('city/edit/<int:pk>/', login_required(CityEditView.as_view()), name='city_edit'),
    path('city/delete/<int:pk>/', login_required(CityDeleteView.as_view()), name='city_delete'),
    path('city/create/', login_required(CityCreateView.as_view()), name='city_create'),
    path('city/load_cities/', load_cities, name='load_cities'),

    path('etrap/', login_required(EtrapListView.as_view()), name='etrap_list'),
    path('etrap/edit/<int:pk>/', login_required(EtrapEditView.as_view()), name='etrap_edit'),
    path('etrap/delete/<int:pk>/', login_required(EtrapDeleteView.as_view()), name='etrap_delete'),
    path('etrap/create/', login_required(EtrapCreateView.as_view()), name='etrap_create'),

    path('education/', login_required(Education_institutionListView.as_view()), name='education_list'),
    path('education/edit/<int:pk>/', login_required(Education_institutionEditView.as_view()), name='education_edit'),
    path('education/delete/<int:pk>/', login_required(Education_institutionDeleteView.as_view()), name='education_delete'),
    path('education/create/', login_required(Education_institutionCreateView.as_view()), name='education_create'),

    path('organization/', login_required(OrganizationListView.as_view()), name='organization_list'),
    path('organization/edit/<int:pk>/', login_required(OrganizationEditView.as_view()), name='organization_edit'),
    path('organization/delete/<int:pk>/', login_required(OrganizationDeleteView.as_view()), name='organization_delete'),
    path('organization/create/', login_required(OrganizationCreateView.as_view()), name='organization_create'),

    path('hospital/', login_required(HospitalListView.as_view()), name='hospital_list'),
    path('hospital/edit/<int:pk>/', login_required(HospitalEditView.as_view()), name='hospital_edit'),
    path('hospital/delete/<int:pk>/', login_required(HospitalDeleteView.as_view()), name='hospital_delete'),
    path('hospital/create/', login_required(HospitalCreateView.as_view()), name='hospital_create'),

    path('doctor/', login_required(DoctorListView.as_view()), name='doctor_list'),
    path('doctor/edit/<int:pk>/', login_required(DoctorEditView.as_view()), name='doctor_edit'),
    path('doctor/delete/<int:pk>/', login_required(DoctorDeleteView.as_view()), name='doctor_delete'),
    path('doctor/create/', login_required(DoctorCreateView.as_view()), name='doctor_create'),

    path('unit/', login_required(UnitListView.as_view()), name='unit_list'),
    path('unit/edit/<int:pk>/', login_required(UnitEditView.as_view()), name='unit_edit'),
    path('unit/delete/<int:pk>/', login_required(UnitDeleteView.as_view()), name='unit_delete'),

    path('surgery_type/', login_required(SurgeryTypeListView.as_view()), name='surgery_type_list'),
    path('surgery_type/edit/<int:pk>/', login_required(SurgeryTypeEditView.as_view()), name='surgery_type_edit'),
    path('surgery_type/delete/<int:pk>/', login_required(SurgeryTypeDeleteView.as_view()), name='surgery_type_delete'),
    path('surgery_type/create/', login_required(SurgeryTypeCreateView.as_view()), name='surgery_type_create'),
]

health/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView

from health import settings

urlpatterns = [
    # path('', TemplateView.as_view(template_name='main_page/main_page.html'), name='main_page'),
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('patients/', include('patients.urls')),
    path('therapy/', include('therapy.urls')),
    path('surgery/', include('surgery.urls')),
    path('investment/', include('investment.urls')),
    path('dicts/', include('dicts.urls')),
    path('diagnosis/', include('diagnosis.urls')),
    path('resolution/', include('resolution.urls')),
    path('reports/', include('reports.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
]
              #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main_page/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import MainPageView


app_name = 'main_page'

urlpatterns = [
    path('', login_required(MainPageView.as_view()), name='main_page'),
]

patients/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientListView, PatientCreateFormView, PatientEditFormView, PatientDeleteView

app_name = 'patients'

urlpatterns = [
    path('list/', login_required(PatientListView.as_view()), name='patient_list'),
    path('create/', login_required(PatientCreateFormView.as_view()), name='patient_create'),
    path('edit/<int:pk>/', login_required(PatientEditFormView.as_view()), name='patient_edit'),
    path('delete/<int:pk>/', login_required(PatientDeleteView.as_view()), name='patient_delete'),
]

surgery/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from .views import PatientSurgeryListView, SurgeryCreateStepOneView, SurgeryCreateStepOneViewWithID, \
    SurgeryCreateStepTwoView, SurgeryEditView

app_name = 'surgery'

urlpatterns = [
    path('list/', login_required(PatientSurgeryListView.as_view()), name='surgery_list'),
    # re_path('list/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)$',
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientSurgeryListView.as_view()), name='surgery_list_period'),
    path('create_one/', login_required(SurgeryCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(SurgeryCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(SurgeryCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(SurgeryEditView.as_view()), name='surgery_edit'),
]

therapy/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientTherapyListView, TherapyCreateStepOneView, TherapyCreateStepTwoView, \
    TherapyCreateStepOneViewWithID, TherapyEditView


app_name = 'therapy'

urlpatterns = [
    path('list/', login_required(PatientTherapyListView.as_view()), name='therapy_list'),
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientTherapyListView.as_view()), name='therapy_list_period'),
    path('create_one/', login_required(TherapyCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(TherapyCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(TherapyCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(TherapyEditView.as_view()), name='therapy_edit'),
]

main_page/views.py
import datetime

from dateutil.relativedelta import relativedelta
from django.db.models import Count, Sum
from django.utils.timezone import now
from django.views.generic import TemplateView

from diagnosis.models import PatientDiagnosis
from health import settings
from investment.models import Investment
from reports.models import PatientEvent
from reports.views import ReportInfoView
from surgery.models import PatientSurgery
from therapy.models import PatientTherapy


class MainPageView(TemplateView):
    template_name = 'main_page/main_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['start_year'] = f'{now().year}-1-1'
        context['end_year'] = f'{now().year}-12-31'

        context['start_month'] = f'{now().year}-{now().month}-1'
        context['end_month'] = datetime.datetime.strftime(
            datetime.date(now().year, now().month, 1) + relativedelta(months=1), '%Y-%m-%d')



        context['surgery_total'] = PatientSurgery.objects\
                                                 .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['surgery_year'] = PatientSurgery.objects\
                                                .filter(surgery_date__year=now().year)\
                                                .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['therapy_total'] = PatientTherapy.objects\
                                                 .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['therapy_year'] = PatientTherapy.objects\
                                                .filter(exit_date__year=now().year)\
                                                .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['diagnosis_total'] = PatientDiagnosis.objects\
                                                     .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['diagnosis_year'] = PatientDiagnosis.objects\
                                                    .filter(exit_date__year=now().year)\
                                                    .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['investment_total'] = Investment.objects\
                                                .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['investment_year'] = Investment.objects\
                                               .filter(investment_date__year=now().year)\
                                               .aggregate(count=Count('id'), sum=Sum('price_man'))
        context['patient_events'] = PatientEvent.objects.all()[:settings.LIST_PAGE_SIZE]
        return context

templates/main_page/find_form.html
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5 class="h5 text-primary"> {% trans "Поиск" %} </h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                    <p>
{#                        <label for="id_name">ФИО пациента:</label>#}
                        <input type="text" name="username" class="form-input form-control" maxlength="150" required id="id_username" placeholder="{% trans "ФИО пациента" %}">
                    </p>
                    <p>
{#                        <label for="id_name">Адрес больницы:</label>#}
                        <input type="text" name="username" class="form-input form-control" maxlength="150" required id="id_username" placeholder="{% trans "Адрес больницы" %}">
                    </p>
                    <p>
{#                        <label for="id_name">Дата операции:</label>#}
                        <input type="text" name="username" class="form-input form-control" maxlength="150" required id="id_username" placeholder="{% trans "Дата операции" %}">
                    </p>

                    <button type="submit" class="btn btn-primary">{% trans "Найти" %}</button>
            </form>

        </div>
    </div>
</div>

templates/main_page/info.html
{% load i18n %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5 class="h5 text-primary"> {% trans "Информация" %} </h4>
        </div>
        <div class="card-body">
            <ul>
                <li class="fw-bold">{% trans "Операций" %}:</li>
                <ul>
                    <li class="fw-medium">{% trans "Всего" %}: - {{ surgery_total.count }} / {{ surgery_total.sum }} </li>
                    <li>{% trans "За год" %}: - {{ surgery_year.count }} / {{ surgery_year.sum }} </li>
                </ul>
                <li class="fw-bold">{% trans "Использовано" %}:</li>
                <ul>
                    <li class="fw-medium">{% trans "Всего" %}: - {{ investment_total.count }} / {{ investment_total.sum }} </li>
                    <li>{% trans "За год" %}:- {{ investment_year.count }} / {{ investment_year.sum }} </li>
                </ul>
            </ul>
        </div>
    </div>
</div>

templates/main_page/last_records.html
{% load i18n %}

<div class="container" style="padding-top: 2vh">
    <div class="card">
        <div class="card-header">
            <h5 class="h5 text-primary"> Последние записи </h5>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">{% trans "Добавлено" %}</th>
                        <th scope="col">{% trans "Тип записи" %}</th>
                        <th scope="col">{% trans "Дата события" %}</th>
                        <th scope="col">{% trans "Дополнительно" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for record in patient_events %}
                    <tr class="pointer" onclick="document.location = '{{ record.link }}'">
                        <th scope="row" >{{forloop.counter}}</th>
                        <td >{{ record.created_at|date:'d-m-Y H:i' }}</td>
                        <td >{{ record.event_name }}</td>
                        <td >{{ record.event_date|date:'d-m-Y' }}</td>
                        <td >{{ record.description }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

templates/main_page/links.html
{% load i18n %}
<div class="container">
    <div class="card">
        <div class="card-header">
            <h5 class="h5 text-primary"> {% trans "Быстрые действия" %} </h5>
        </div>
        <div class="card-body">
            <div> <a class="link-primary" href="{% url 'patients:patient_create' %}">{% trans "Новый пациент" %}</a> </div>
            <div> <a class="link-primary" href="{% url 'resolutions:resolution_create' %}">{% trans "Новое решение" %}</a> </div>
            <div> <a href="{% url 'surgery:create_one' %}">{% trans "Добавить запись об операции" %}</a> </div>
            <div> <a href="{% url 'therapy:create_one' %}">{% trans "Добавить запись о лечении" %}</a> </div>
            <div> <a href="{% url 'diagnosis:create_one' %}">{% trans "Добавить запись о диагностике" %}</a> </div>
            <div> <a href="{% url 'investment:create' %}">{% trans "Добавить запись об использовании средств" %}</a> </div>
        </div>
    </div>
</div>

templates/main_page/main_page.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
    <div class="row">
        <div class="col-4">
            {% include "reports/info.html" %}
        </div>
{#        <div class="col">#}
{#            {% include "main_page/find_form.html" %}#}
{#        </div>#}
        <div class="col-4">
            {% include "main_page/links.html" %}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% include "main_page/last_records.html" %}
        </div>
    </div>

{% endblock %}

{% block additional_script %}
<script>
    var link_surgery_total = document.getElementsById("id_link_surgery_total");
    link_surgery_total.addEventListener("click", function(event) {
        event.preventDefault();
        var xhr = new XMLHttpRequest();
        xhr.open('POST', {% url 'surgery:surgery_list' %});
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function() {
            if (xhr.status === 200) {
                console.log(xhr.responseText);
            }
        };
        var params = 'date_start=2023-09-01&date_end=2023-09-31&etrap=-1';
        xhr.send(params);
    });

    var link_surgery_year = document.getElementsById("id_link_surgery_year");
    link_surgery_year.addEventListener("click", function(event) {
        event.preventDefault();
        var xhr = new XMLHttpRequest();
        xhr.open('POST', link_surgery_year.href);
        xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
        xhr.onload = function() {
            if (xhr.status === 200) {
                console.log(xhr.responseText);
            }
        };
        var params = 'date_start={{ start_year }}&date_end={{ end_year }}&etrap=-1';
        xhr.send(params);
    });
</script>
{% endblock %}