dicts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DictsView, CityListView, CityEditView, CityCreateView, CityDeleteView, \
    EtrapListView, EtrapEditView, EtrapCreateView, EtrapDeleteView, \
    Education_institutionListView, Education_institutionEditView, Education_institutionCreateView, \
    Education_institutionDeleteView, OrganizationListView, OrganizationEditView, OrganizationCreateView, \
    OrganizationDeleteView, HospitalListView, HospitalEditView, HospitalCreateView, HospitalDeleteView, DoctorListView, \
    DoctorEditView, DoctorCreateView, DoctorDeleteView, UnitListView, UnitEditView, UnitCreateView, UnitDeleteView, \
    load_cities, SurgeryTypeListView, SurgeryTypeEditView, SurgeryTypeDeleteView, SurgeryTypeCreateView

app_name = 'dicts'

urlpatterns = [
    path('', login_required(DictsView.as_view()), name='dicts_list'),

    path('city/', login_required(CityListView.as_view()), name='city_list'),
    path('city/edit/<int:pk>/', login_required(CityEditView.as_view()), name='city_edit'),
    path('city/delete/<int:pk>/', login_required(CityDeleteView.as_view()), name='city_delete'),
    path('city/create/', login_required(CityCreateView.as_view()), name='city_create'),
    path('city/load_cities/', load_cities, name='load_cities'),

    path('etrap/', login_required(EtrapListView.as_view()), name='etrap_list'),
    path('etrap/edit/<int:pk>/', login_required(EtrapEditView.as_view()), name='etrap_edit'),
    path('etrap/delete/<int:pk>/', login_required(EtrapDeleteView.as_view()), name='etrap_delete'),
    path('etrap/create/', login_required(EtrapCreateView.as_view()), name='etrap_create'),

    path('education/', login_required(Education_institutionListView.as_view()), name='education_list'),
    path('education/edit/<int:pk>/', login_required(Education_institutionEditView.as_view()), name='education_edit'),
    path('education/delete/<int:pk>/', login_required(Education_institutionDeleteView.as_view()), name='education_delete'),
    path('education/create/', login_required(Education_institutionCreateView.as_view()), name='education_create'),

    path('organization/', login_required(OrganizationListView.as_view()), name='organization_list'),
    path('organization/edit/<int:pk>/', login_required(OrganizationEditView.as_view()), name='organization_edit'),
    path('organization/delete/<int:pk>/', login_required(OrganizationDeleteView.as_view()), name='organization_delete'),
    path('organization/create/', login_required(OrganizationCreateView.as_view()), name='organization_create'),

    path('hospital/', login_required(HospitalListView.as_view()), name='hospital_list'),
    path('hospital/edit/<int:pk>/', login_required(HospitalEditView.as_view()), name='hospital_edit'),
    path('hospital/delete/<int:pk>/', login_required(HospitalDeleteView.as_view()), name='hospital_delete'),
    path('hospital/create/', login_required(HospitalCreateView.as_view()), name='hospital_create'),

    path('doctor/', login_required(DoctorListView.as_view()), name='doctor_list'),
    path('doctor/edit/<int:pk>/', login_required(DoctorEditView.as_view()), name='doctor_edit'),
    path('doctor/delete/<int:pk>/', login_required(DoctorDeleteView.as_view()), name='doctor_delete'),
    path('doctor/create/', login_required(DoctorCreateView.as_view()), name='doctor_create'),

    path('unit/', login_required(UnitListView.as_view()), name='unit_list'),
    path('unit/edit/<int:pk>/', login_required(UnitEditView.as_view()), name='unit_edit'),
    path('unit/delete/<int:pk>/', login_required(UnitDeleteView.as_view()), name='unit_delete'),

    path('surgery_type/', login_required(SurgeryTypeListView.as_view()), name='surgery_type_list'),
    path('surgery_type/edit/<int:pk>/', login_required(SurgeryTypeEditView.as_view()), name='surgery_type_edit'),
    path('surgery_type/delete/<int:pk>/', login_required(SurgeryTypeDeleteView.as_view()), name='surgery_type_delete'),
    path('surgery_type/create/', login_required(SurgeryTypeCreateView.as_view()), name='surgery_type_create'),
]

health/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView

from health import settings

urlpatterns = [
    # path('', TemplateView.as_view(template_name='main_page/main_page.html'), name='main_page'),
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('patients/', include('patients.urls')),
    path('therapy/', include('therapy.urls')),
    path('surgery/', include('surgery.urls')),
    path('investment/', include('investment.urls')),
    path('dicts/', include('dicts.urls')),
    path('diagnosis/', include('diagnosis.urls')),
    path('resolution/', include('resolution.urls')),
    path('reports/', include('reports.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
]
              #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dicts/models.py
from django.db import models
from django_currentuser.middleware import get_current_authenticated_user

from health.utils import get_data_lang


class Etrap(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=50, blank=True, null=True)
    name_1 = models.CharField(max_length=50, blank=True, null=True)
    name_2 = models.CharField(max_length=50, blank=True, null=True)

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    def __str__(self):
        return f'{self.name}'
    class Meta:
        managed = True
        db_table = 'etrap'
        verbose_name_plural = 'Велаяты/города'
        verbose_name = 'Велаят/город'
        ordering = ['name_0',]


class City(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=50, blank=True, null=True)
    name_1 = models.CharField(max_length=50, blank=True, null=True)
    name_2 = models.CharField(max_length=50, blank=True, null=True)
    etrap = models.ForeignKey(Etrap, on_delete=models.PROTECT, to_field='id')

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = True
        db_table = 'city'
        ordering = ['etrap', 'name_0']
        verbose_name_plural = 'Города/этрапы'
        verbose_name = 'Город/этрап'


class Sex(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=50, blank=True, null=True)
    name_1 = models.CharField(max_length=50, blank=True, null=True)
    name_2 = models.CharField(max_length=50, blank=True, null=True)

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    def __str__(self):
        return f'{self.name}'
    class Meta:
        managed = True
        db_table = 'sex'
        verbose_name_plural = 'Пол'
        verbose_name = 'Пол'


class Education_institution(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=250, blank=True, null=True)
    name_1 = models.CharField(max_length=250, blank=True, null=True)
    name_2 = models.CharField(max_length=250, blank=True, null=True)
    address_0 = models.CharField(max_length=250, blank=True, null=True)
    address_1 = models.CharField(max_length=250, blank=True, null=True)
    address_2 = models.CharField(max_length=250, blank=True, null=True)
    etrap = models.ForeignKey(Etrap, on_delete=models.PROTECT, to_field='id',
                              blank=True, null=True,
                              related_name='relation_education_institution_etrap')
    city = models.ForeignKey(City, on_delete=models.PROTECT, to_field='id', related_name='relation_education_institution_city')

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    @property
    def address(self):
        if get_data_lang() == 'en':
            return self.address_0
        elif get_data_lang() == 'tk':
            return self.address_2
        else:
            return self.address_1

    class Meta:
        managed = True
        db_table = 'education_institution'
        verbose_name_plural = 'Учебные заведения'
        verbose_name = 'Учебное заведение'
        ordering = ['name_0',]

    def __str__(self):
        return f'{self.name}, {self.city}'


class Hospital(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=250, blank=True, null=True)
    name_1 = models.CharField(max_length=250, blank=True, null=True)
    name_2 = models.CharField(max_length=250, blank=True, null=True)
    address_0 = models.CharField(max_length=250, blank=True, null=True)
    address_1 = models.CharField(max_length=250, blank=True, null=True)
    address_2 = models.CharField(max_length=250, blank=True, null=True)
    etrap = models.ForeignKey(Etrap, on_delete=models.PROTECT, to_field='id',
                              blank=True, null=True,
                              related_name='relation_hospital_etrap')
    city = models.ForeignKey(City, on_delete=models.PROTECT, to_field='id', related_name='relation_hospital_city')

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    @property
    def address(self):
        if get_data_lang() == 'en':
            return self.address_0
        elif get_data_lang() == 'tk':
            return self.address_2
        else:
            return self.address_1
    def __str__(self):
        return f'{self.name}, {self.city}'

    class Meta:
        managed = True
        db_table = 'hospital'
        verbose_name_plural = 'Больницы'
        verbose_name = 'Больница'
        ordering = ['name_0',]


class Doctor(models.Model):
    id = models.AutoField(primary_key=True)
    fullname_0 = models.CharField(max_length=150, blank=True, null=True)
    fullname_1 = models.CharField(max_length=150, blank=True, null=True)
    fullname_2 = models.CharField(max_length=150, blank=True, null=True)
    date_birthday = models.DateField(blank=True, null=True)

    hospital = models.ForeignKey(Hospital, on_delete=models.PROTECT, to_field='id')

    sex = models.ForeignKey(Sex, on_delete=models.PROTECT, to_field='id')

    class Meta:
        managed = True
        db_table = 'doctor'
        ordering = ['fullname_0']
        verbose_name_plural = 'Врачи'
        verbose_name = 'Врач'

    def __str__(self):
        return f'{self.fullname}'

    @property
    def fullname(self):
        if get_data_lang() == 'en':
            return self.fullname_0
        elif get_data_lang() == 'tk':
            return self.fullname_2
        else:
            return self.fullname_1


class Unit(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=150, blank=True, null=True)
    name_1 = models.CharField(max_length=150, blank=True, null=True)
    name_2 = models.CharField(max_length=150, blank=True, null=True)

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = True
        db_table = 'unit'
        verbose_name_plural = 'Ед. измерения'
        verbose_name = 'Ед. измерения'
        ordering = ['name_0',]


class SurgeryType(models.Model):
    id = models.AutoField(primary_key=True)
    name_0 = models.CharField(max_length=50, blank=True, null=True)
    name_1 = models.CharField(max_length=50, blank=True, null=True)
    name_2 = models.CharField(max_length=50, blank=True, null=True)

    @property
    def name(self):
        if get_data_lang() == 'en':
            return self.name_0
        elif get_data_lang() == 'tk':
            return self.name_2
        else:
            return self.name_1
    def __str__(self):
        return f'{self.name}'

    class Meta:
        managed = True
        db_table = 'surgery_type'
        verbose_name_plural = 'Тип операции'
        verbose_name = 'Типы операций'
        ordering = ['name_0',]


templates/dicts/city.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <div class="card col-6">
        <div class="card-header">
            <h5 class="text-primary">{{ title }}</h5>
        </div>
        <div class="card-body">
            <form method="post" >
            {% if not error is None %}
                <p class="text-danger">{% trans "Ошибка" %}: {{ error|default_if_none:'' }} </p>
            {% endif %}
                {% crispy form %}
            </form>
        </div>
    </div>
{% endblock %}

{% block additional_script %}
    <script>
        $("#id_etrap").change(function () {
            var url = "{% url 'dicts:load_cities' %}";
            var etrapId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'etrap': etrapId
                },
                success: function (data) {
                    $("#id_city").html("");
                    for (var i = 0; i < data.length; i++) {
                        var option = new Option(data[i].name, data[i].id);
                        $("#id_city").append(option);
                    }
                }
            });
        });
        </script>
{% endblock %}

templates/dicts/city_confirm_delete.html
{% extends 'base.html' %}
{%  block content %}
{% load i18n %}
<form method="post">{% csrf_token %}
    <p class="h4" style="padding-bottom: 2vh;">{% trans "Вы действительно ходите удалить запись?" %}
        "{{ object }}"?</p>
    {{ form }}
    <input type="submit" class="btn btn-danger" value="{% trans "Удалить" %}">
    <a type="submit" class="btn btn-secondary" onclick="history.back()">{% trans "Отмена" %}</a>
</form>
{% endblock %}

templates/dicts/city_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}
    <div class="row justify-content-center align-items-center">
        <div class="col col-6">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th class="text-primary">
                            <div class="row">
                                <div class="col col-1">
                                    <a class="bg-transparent text-decoration-none text-black"
                                         href="{{ request.path }}create/">
                                    <img src="{% static "images/add_blue.png" %}" height="36" width="36" alt="">
                                    </a>
                                </div>
                                <div class="col col-9">
                                    {{ list_title }} ({{ object_list.count|default_if_none:'0' }})
                                </div>
                            </div>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for rec in object_list %}
                        <tr>
                            <td>
                                <a href="{{ request.path }}edit/{{ rec.id }}/">{{ rec }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% include 'pagination.html' %}

        </div>
    </div>

{% endblock %}

templates/dicts/dicts.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
    <h5 class="text-primary">{% trans "Список справочников" %}</h5>
    <ul>
    <li><a href="{% url 'dicts:etrap_list' %}">{% trans "Велаяты (города)" %}</a></li>
    <li><a href="{% url 'dicts:city_list' %}">{% trans "Этрапы (города)" %}</a></li>
    <li><a href="{% url 'dicts:education_list' %}">{% trans "Учебные заведения" %}</a></li>
    <li><a href="{% url 'dicts:organization_list' %}">{% trans "Организации" %}</a></li>
    <li><a href="{% url 'dicts:hospital_list' %}">{% trans "Больницы" %}</a></li>
    <li><a href="{% url 'dicts:doctor_list' %}">{% trans "Врачи" %}</a></li>
    <li><a href="{% url 'dicts:surgery_type_list' %}">{% trans "Типы операций" %}</a></li>
    <li><a href="{% url 'dicts:unit_list' %}">{% trans "Единицы измерения" %}</a></li>
    </ul>

{% endblock %}