dicts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import DictsView, CityListView, CityEditView, CityCreateView, CityDeleteView, \
    EtrapListView, EtrapEditView, EtrapCreateView, EtrapDeleteView, \
    Education_institutionListView, Education_institutionEditView, Education_institutionCreateView, \
    Education_institutionDeleteView, OrganizationListView, OrganizationEditView, OrganizationCreateView, \
    OrganizationDeleteView, HospitalListView, HospitalEditView, HospitalCreateView, HospitalDeleteView, DoctorListView, \
    DoctorEditView, DoctorCreateView, DoctorDeleteView, UnitListView, UnitEditView, UnitCreateView, UnitDeleteView, \
    load_cities, SurgeryTypeListView, SurgeryTypeEditView, SurgeryTypeDeleteView, SurgeryTypeCreateView

app_name = 'dicts'

urlpatterns = [
    path('', login_required(DictsView.as_view()), name='dicts_list'),

    path('city/', login_required(CityListView.as_view()), name='city_list'),
    path('city/edit/<int:pk>/', login_required(CityEditView.as_view()), name='city_edit'),
    path('city/delete/<int:pk>/', login_required(CityDeleteView.as_view()), name='city_delete'),
    path('city/create/', login_required(CityCreateView.as_view()), name='city_create'),
    path('city/load_cities/', load_cities, name='load_cities'),

    path('etrap/', login_required(EtrapListView.as_view()), name='etrap_list'),
    path('etrap/edit/<int:pk>/', login_required(EtrapEditView.as_view()), name='etrap_edit'),
    path('etrap/delete/<int:pk>/', login_required(EtrapDeleteView.as_view()), name='etrap_delete'),
    path('etrap/create/', login_required(EtrapCreateView.as_view()), name='etrap_create'),

    path('education/', login_required(Education_institutionListView.as_view()), name='education_list'),
    path('education/edit/<int:pk>/', login_required(Education_institutionEditView.as_view()), name='education_edit'),
    path('education/delete/<int:pk>/', login_required(Education_institutionDeleteView.as_view()), name='education_delete'),
    path('education/create/', login_required(Education_institutionCreateView.as_view()), name='education_create'),

    path('organization/', login_required(OrganizationListView.as_view()), name='organization_list'),
    path('organization/edit/<int:pk>/', login_required(OrganizationEditView.as_view()), name='organization_edit'),
    path('organization/delete/<int:pk>/', login_required(OrganizationDeleteView.as_view()), name='organization_delete'),
    path('organization/create/', login_required(OrganizationCreateView.as_view()), name='organization_create'),

    path('hospital/', login_required(HospitalListView.as_view()), name='hospital_list'),
    path('hospital/edit/<int:pk>/', login_required(HospitalEditView.as_view()), name='hospital_edit'),
    path('hospital/delete/<int:pk>/', login_required(HospitalDeleteView.as_view()), name='hospital_delete'),
    path('hospital/create/', login_required(HospitalCreateView.as_view()), name='hospital_create'),

    path('doctor/', login_required(DoctorListView.as_view()), name='doctor_list'),
    path('doctor/edit/<int:pk>/', login_required(DoctorEditView.as_view()), name='doctor_edit'),
    path('doctor/delete/<int:pk>/', login_required(DoctorDeleteView.as_view()), name='doctor_delete'),
    path('doctor/create/', login_required(DoctorCreateView.as_view()), name='doctor_create'),

    path('unit/', login_required(UnitListView.as_view()), name='unit_list'),
    path('unit/edit/<int:pk>/', login_required(UnitEditView.as_view()), name='unit_edit'),
    path('unit/delete/<int:pk>/', login_required(UnitDeleteView.as_view()), name='unit_delete'),

    path('surgery_type/', login_required(SurgeryTypeListView.as_view()), name='surgery_type_list'),
    path('surgery_type/edit/<int:pk>/', login_required(SurgeryTypeEditView.as_view()), name='surgery_type_edit'),
    path('surgery_type/delete/<int:pk>/', login_required(SurgeryTypeDeleteView.as_view()), name='surgery_type_delete'),
    path('surgery_type/create/', login_required(SurgeryTypeCreateView.as_view()), name='surgery_type_create'),
]

health/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView

from health import settings

urlpatterns = [
    # path('', TemplateView.as_view(template_name='main_page/main_page.html'), name='main_page'),
    path('', include('main_page.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('patients/', include('patients.urls')),
    path('therapy/', include('therapy.urls')),
    path('surgery/', include('surgery.urls')),
    path('investment/', include('investment.urls')),
    path('dicts/', include('dicts.urls')),
    path('diagnosis/', include('diagnosis.urls')),
    path('resolution/', include('resolution.urls')),
    path('reports/', include('reports.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    re_path(r'^rosetta/', include('rosetta.urls')),
]
              #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

reports/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from .views import ReportPageView, SearchStatisticView, SearchStatisticByVelayatView, SearchHospitalsView, \
    SearchStatisticByMonthView

app_name = 'reports'

urlpatterns = [
    path('', login_required(ReportPageView.as_view()), name='reports'),
    re_path('statistic/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)/(?P<etrap>[-]?[0-9]+)/\\Z',
            login_required(SearchStatisticView.as_view()), name='report_statistic'),
    re_path('statistic_by_velayat/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)$',
            login_required(SearchStatisticByVelayatView.as_view()), name='statistic_by_velayat'),
    re_path('statistic_by_month/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)/(?P<etrap>[-]?[0-9]+)/\\Z',
            login_required(SearchStatisticByMonthView.as_view()), name='statistic_by_month'),
    re_path('hospitals/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)$',
            login_required(SearchHospitalsView.as_view()), name='hospitals'),
]

surgery/urls.py
from django.urls import path, re_path
from django.contrib.auth.decorators import login_required

from .views import PatientSurgeryListView, SurgeryCreateStepOneView, SurgeryCreateStepOneViewWithID, \
    SurgeryCreateStepTwoView, SurgeryEditView

app_name = 'surgery'

urlpatterns = [
    path('list/', login_required(PatientSurgeryListView.as_view()), name='surgery_list'),
    # re_path('list/(?P<date_start>[^/]+)/(?P<date_end>[^/]+)$',
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientSurgeryListView.as_view()), name='surgery_list_period'),
    path('create_one/', login_required(SurgeryCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(SurgeryCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(SurgeryCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(SurgeryEditView.as_view()), name='surgery_edit'),
]

therapy/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import PatientTherapyListView, TherapyCreateStepOneView, TherapyCreateStepTwoView, \
    TherapyCreateStepOneViewWithID, TherapyEditView


app_name = 'therapy'

urlpatterns = [
    path('list/', login_required(PatientTherapyListView.as_view()), name='therapy_list'),
    path('list_period/<str:date_start>/<str:date_end>/',
         login_required(PatientTherapyListView.as_view()), name='therapy_list_period'),
    path('create_one/', login_required(TherapyCreateStepOneView.as_view()), name='create_one'),
    path('create_one_id/<int:id>/', login_required(TherapyCreateStepOneViewWithID.as_view()), name='create_one_id'),
    path('create_two/', login_required(TherapyCreateStepTwoView.as_view()), name='create_two'),
    path('edit/<int:pk>/', login_required(TherapyEditView.as_view()), name='therapy_edit'),
]

users/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from .views import SignUpView, LoginUserView, logout_user, AsdUserChangeView, PasswordChangeView


app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', login_required(logout_user), name='logout'),
    path('profile/<int:pk>/', login_required(AsdUserChangeView.as_view()), name='profile'),
    path('password_change/', login_required(PasswordChangeView.as_view()), name='password_change'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


{#    <link rel="stylesheet" href={% static "css/../static/css-bak/bootstrap.min.css" %}>#}
    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
{#    <link rel="stylesheet" href={% static "css/select2.min.css" %}>#}
    <link rel="stylesheet" href={% static "css/easy_select2.css" %}>
    <link rel="stylesheet" href={% static "css/main.css" %}>


    <title>{% block title %}Тест - Фонд{% endblock %}</title>

    <link rel="shortcut icon" href={% static 'images/favicon.ico' %}

</head>
<body>

<!-- Pre Header -->
    <div id="pre-header">
      <div class="container">
        <div class="row outer-line ">
            <div class="col-1 inner-line">
                <a class="" href="{% url 'main_page:main_page' %}">
                    <img src={% static "images/logo.png" %} alt=""
                         width="76" height="75" class="align-content-center">
                </a>
            </div>
          <div class="col-7 inner-line" style="padding: 5px">
            <span>Фонд помощи детям,<br>
                нуждающимся в защите</span>
          </div>
            {% if user.is_authenticated %}
            <div class="col-4 inner-line">
                {% if user.is_authenticated %}
                    <div class="table" style="display: inline;">
                        <div class="row align-items-center">
                            <div class="col-4">
                                <div class="row" style="padding-bottom: 0;">
                                    <div class="col">
                                        <a class="inner-line"  href="{% url "users:profile" user.pk %}">
{#                                         <strong>{{ user.last_name|title }} {{ user.first_name.0|upper }}.#}
                                         <strong>{{ user.username }}
                                         </strong></a>
                                    </div>
                                </div>
{#                                <div class="row" style="padding-top: 0;">#}
{#                                    <div class="col">#}
{#                                         <p class="text-start" style="display: inline; ">{% trans user.group_name %}</p>#}
{#                                    </div>#}
{#                                </div>#}
{#                                <p class="text-start" style="display: inline; "><strong>Admin</strong>#}
{#                                    Администратор#}
{#                                </p>#}
                            </div>
                            <div class="col-8">
{#                                <a class="inner-line"  href="{% url "users:profile" user.pk %}">#}
{#                                    <img src="{% static "images/profile.png" %}" width="50" height="40" style="display: inline; padding-right: 0.2vw; padding-left: 0 ">#}
{#                                </a>#}
                                <a class="inner-line" href="{% url 'users:logout' %}">
                                    <img src="{% static "images/exit.png" %}" width="50" height="40" style="display: inline;">
                                </a>
                            </div>
                        </div>

                    </div>
                {% else %}
{#                    <a href="#">Зарегистрироваться</a>#}
                {% endif %}
          </div>
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Navigation -->
{% if user.is_authenticated %}
    <nav class="navbar navbar-expand-lg bg-menu static-top">
      <div class="container">
{#        <a class="navbar-brand" href="#"><img src="{% static "images/edit.png" %}" width="30" height="30" alt=""></a>#}

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item {% if request.path == '/' %} active {% endif %}">
              <a class="nav-link" href="{% url 'main_page:main_page' %}" >{%  trans "Главная" %}
              </a>
            </li>
            <li class="nav-item {% if 'patients' in request.path %} active {% endif %}">
              <a class="nav-link" href="{% url "patients:patient_list" %}">{%  trans "Пациенты" %}</a>
                 <ul>
                    <li><a class="nav-link" href="{% url 'patients:patient_list' %}">{%  trans "Пациенты" %}</a></li>
                    <li><a class="nav-link" href="{% url 'resolutions:resolution_list' %}">{%  trans "Решения" %}</a></li>
                </ul>
            </li>
            <li class="nav-item {% if 'therapy' in request.path or 'surgery' in request.path %} active {% endif %} ">
                  <a class="nav-link" href="{% url 'surgery:surgery_list' %}">{%  trans "Лечение" %}</a>
                 <ul>
                    <li><a class="nav-link" href="{% url 'surgery:surgery_list' %}">{%  trans "Операции" %}</a></li>
                    <li><a class="nav-link" href="{% url 'therapy:therapy_list' %}">{%  trans "Лечение" %}</a></li>
                    <li><a class="nav-link" href="{% url 'diagnosis:diagnosis_list' %}">{%  trans "Диагностика" %}</a></li>
                </ul>
            </li>

            <li class="nav-item {% if 'investment' in request.path %} active {% endif %}">
              <a class="nav-link" href="{% url 'investment:investment_list' %}">{%  trans "Использование" %}</a>
            </li>
            <li class="nav-item {% if 'reports' in request.path %} active {% endif %}">
              <a class="nav-link" href="{% url 'reports:reports' %}">{%  trans "Отчёты" %}</a>
            </li>
            <li class="nav-item {% if 'dicts' in request.path %} active {% endif %}">
              <a class="nav-link" href="{% url 'dicts:dicts_list' %}">{%  trans "Справочники" %}</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
{% endif %}

    <div class="container" style="padding-top: 5vh; padding-bottom: 5vh;">
{% if user.is_authenticated or 'login' in request.path %}
        {% block content %}

        {% endblock %}
{% else %}
  <p>{%  trans "Необходимо войти в систему" %}</p>
  <a href="{% url 'users:login' %}">{%  trans "Вход" %}</a> |
  <a href="{% url 'users:signup' %}">{%  trans "Регистрация" %}</a>
{% endif %}

    </div>

    <!-- Sub Footer Starts Here -->
    <div class="sub-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="copyright-text">
              <p>Copyright &copy; 2023 KP

{#                - Design: <a rel="nofollow" href="#">Asd</a></p>#}
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Sub Footer Ends Here -->

{%  block script %}
        <script src={% static 'js/jquery/jquery.js' %}></script>
        <script src={% static 'js/jquery.init.js' %}></script>
        <script src={% static "js/bootstrap.min.js" %}></script>
        <script src={% static "js/bootstrap.bundle.min.js" %}></script>
        <script src={% static "js/bootstrap-tab.js" %}></script>
        <script src={% static 'js/init.js' %}></script>
        <script src={% static 'js/easy_select2.js' %}></script>
        <script src={% static 'js/select2.js' %}></script>
{#        <script type="text/javascript" src="{% static 'js/init.js' %}"></script>#}
{% endblock script %}
{%  block additional_script %}


{% endblock additional_script %}
</body>
</html>

templates/base_main.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}


{% if user.is_authenticated %}
    <div class="top-line">
  Hi {{ user.username }}!
  <p><a href="{% url 'users:logout' %}">logout</a></p>
    </div>
    content:
{% block content %}

{% endblock %}

    
{% else %}
  <p>Необходимо войти в систему</p>
  <a href="{% url 'users:login' %}">Вход</a> |
  <a href="{% url 'users:signup' %}">Регистрация</a>
{% endif %}

templates/create_one.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
{% if user.is_authenticated %}

    <form method="post" >
        {% if not error is None %}
            <p class="text-danger">{% trans "Ошибка" %}: {{ error|default_if_none:'' }} </p>
        {% endif %}
        <div class="col-5">
            <p class="text-primary h5" style="padding-bottom: 1vh">
                {% if object.id %}
                    {% trans "Пациент" %}: {{ object.fullname }}
                {% else %}
                    {% trans "Новый пациент" %}
                {% endif %}
            </p>
        </div>
            {% crispy form %}
    </form>

{% else %}
  <p>{% trans "Необходимо войти в систему" %}</p>
  <a href="{% url 'users:login' %}">{% trans "Вход" %}</a> |
  <a href="{% url 'users:signup' %}">{% trans "Регистрация" %}</a>
{% endif %}
{% endblock %}

templates/create_two.html

{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}

{% block content %}
{% if user.is_authenticated %}

    {% if object.patient_id %}
    <p class="h5 text-primary"> {{ title }} (
        <a class="h5 link-primary" href="{% url 'patients:patient_edit' object.patient_id %}">
            {% trans "Пациент" %}: {{ object.patient }}
        </a>)
    </p>
    {% endif %}
    <form method="post" >
    {% if not error is None %}
        <p class="text-danger">{% trans "Ошибка" %}: {{ error|default_if_none:'' }} </p>
    {% endif %}
        {% crispy form %}
    </form>

{% else %}
  <p>{% trans "Необходимо войти в систему" %}</p>
  <a href="{% url 'users:login' %}">{% trans "Вход" %}</a> |
  <a href="{% url 'users:signup' %}">{% trans "Регистрация" %}</a>
{% endif %}
{% endblock %}

templates/pagination.html
{% load i18n %}
{% if is_paginated %}
    <div class="pagination justify-content-center">
        <span class="page-link">
            {% if page_obj.has_previous %}
                <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"> {% trans "Предыдущая" %} </a>
{#                <a href="{% url url_list %}?page={{ page_obj.previous_page_number }}"> {% trans "Предыдущая" %} </a>#}
            {% endif %}
            <span class="text-black-50">
                <span style="padding: 1em">{{ page_obj.number }}</span>
            </span>
            {% if page_obj.has_next %}
                <a href="{{ request.path }}?page={{ page_obj.next_page_number }}"> {% trans "Следующая" %} </a>
{#                <a href="{% url url_list %}?page={{ page_obj.next_page_number }}"> {% trans "Следующая" %} </a>#}
            {% endif %}
        </span>
    </div>
{% endif %}

templates/patient_menu.html
{% load i18n %}
        <div class="row" style="padding-bottom: 1vh;">
            <a class="col col-4 btn
                      {% if 'patient' in request.path  %} btn-primary {% else %} btn-outline-secondary {% endif %}
                      text-decoration-none text-black-50 fw-bold" style="margin: 5px"
                        href="{% url 'patients:patient_list' %}">
                {% trans "Пациенты" %}
                {% if patient_list %}
                    ({{ patient_list.count|default_if_none:'0' }})
                {% endif %}
            </a>
            <a class="col col-4 btn
                      {% if 'resolution' in request.path  %} btn-primary {% else %} btn-outline-secondary {% endif %}
                      text-decoration-none text-black-50 fw-bold" style="margin: 5px"
                        href="{% url 'resolutions:resolution_list' %}">
                {% trans "Решения" %}
                {% if resolution_list %}
                    ({{ resolution_list.count|default_if_none:'0' }})
                {% endif %}
            </a>
        </div>

templates/search_panel.html
{% load i18n %}
{% load crispy_forms_tags %}
            <div class="col-10">
                <div class="panel-group">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <p class="panel-title">
                        <button class="btn btn-light btn-link" onclick="$('#form-panel').toggle();"
                                  >
                            {% trans "Панель поиска" %}
                        </button>
{#                        <a data-bs-toggle="collapse" href="#" onclick="$('#form-panel').toggle();">{% trans "Панель поиска" %}</a>#}
                      </p>
                    </div>
                    <div id="form-panel" class="panel-collapse collapse">
                      <div class="panel-body">
                        <form method="post">
                            {% crispy form %}
                        </form>
                      </div>
                      <div class="panel-footer"></div>
                    </div>
                  </div>
                </div>

{#                <button class="btn btn-primary" type="button"#}
{#                        data-bs-toggle="collapse"#}
{#                        data-bs-target="#form"#}
{#                        aria-expanded="false" aria-controls="form" >#}
{#                    {% trans "Поиск" %}</button>#}
{#                <form method="post" class="collapse" id="form">#}
{#                    {% crispy form %}#}
{#                </form>#}

            </div>

templates/therapy_menu.html
{% load i18n %}
        <div class="row" style="padding-bottom: 1vh;">
            <a class="col btn
                      {% if 'surgery' in request.path  %} btn-primary {% else %} btn-outline-secondary {% endif %}
                      text-decoration-none text-black-50 fw-bold" style="margin: 5px"
                        href="{% url 'surgery:surgery_list' %}">
                {% trans "Операции" %}
                {% if surgery_list %}
                    ({{ surgery_list.count|default_if_none:'0' }})
                {% endif %}
            </a>
            <a class="col btn
                      {% if 'therapy' in request.path  %} btn-primary {% else %} btn-outline-secondary {% endif %}
                      text-decoration-none text-black-50 fw-bold" style="margin: 5px"
                        href="{% url 'therapy:therapy_list' %}">
                {% trans "Лечение" %}
                {% if therapy_list %}
                    ({{ therapy_list.count|default_if_none:'0' }})
                {% endif %}
            </a>
            <a class="col btn
                      {% if 'diagnosis' in request.path  %} btn-primary {% else %} btn-outline-secondary {% endif %}
                      text-decoration-none text-black-50 fw-bold" style="margin: 5px"
                        href="{% url 'diagnosis:diagnosis_list' %}">
                {% trans "Диагностика" %}
                {% if diagnosis_list %}
                    ({{ diagnosis_list.count|default_if_none:'0' }})
                {% endif %}
            </a>
        </div>